### ISSUE TITLE
Won't compile for macOS projects

### ISSUE THREAD

**Issue by bartreardon** [shaps80/MarkdownText#2]
## General Information

 - Project version:
 
 
 - Platform/OS version: 
 
macOS 11+
 
 - IDE version:
 
Xcode 14
 
## Describe the bug
Compiling MackdownText in a macOS project fails with the SwiftUIBackports dependency calling UIScreen which is not present under macOS. https://github.com/shaps80/SwiftUIBackports/blob/d9842f24656ff7c6116dc207b60f0b6d302a5a9a/Sources/SwiftUIBackports/Shared/ImageRenderer/Renderer.swift#L7   

## Steps to reproduce
Create a new macOS SwiftUI project. Import MarkdownText. Add a simple `MarkdownText("<some_markdown") to your view.

## Expected behavior
The README.md claims this is supported under macOS but the dependencies are not.

## Screenshots
![image](https://user-images.githubusercontent.com/3598965/193994629-899b6049-dcdf-4a33-9136-e42cd48aefb5.png)

## Additional context
Currently looking for an alternate to MarkdownUI for supporting markdown in a macOS project to run under macOS 11 or newer (so unable to take advantage of built in markdown capability)

**Comment by shaps80** [comment]
Oh nice catch! Not sure how that slipped through.

**Comment by shaps80** [comment]
Closing as this is now resolved
