### ISSUE TITLE
How get text can be selected

### ISSUE THREAD

**Issue by iHTCboy** [shaps80/MarkdownText#3]
1. How can I set the displayed text, which can be selected and copied. 
2. In addition, the height of the code, is there any implementation method or idea.

Thanks for open source~

**Comment by shaps80** [comment]
@iHTCboy 

1. Selection won’t be possible here to be honest, since this isn’t supported by `Text` in general. No to mention, the styling APIs wouldn’t work if it was all `Text` so each block can be essentially _any_ type of `View`. Sorry ¯\_(ツ)_/¯

2. I’m not sure what you’re asking for here?

**Comment by iHTCboy** [comment]
@shaps80 thanks！

I would like to ask that the color highlighted by the code is not only one color, for example:

```
let myName = "Swift AI"
print("Hello, \(myName)")
```

```Swift
let myName = "Swift AI"
print("Hello, \(myName)")

**Comment by shaps80** [comment]
I understand. So for syntax highlighting (which would be the appropriate addition) we'd need to include a parser for languages (Tree-Sitter for example) and then we'd need to extend the configuration for `MarkdownCodeStyle` to provide an AST of the code itself.

That way we can provide styling per token, and even include default 'themes' etc.

I'm more than happy for you to contribute that but I'm very busy on other projects atm, so it will be some time before I have the capacity to spend on this 👍

If you do explore this, please open a draft PR so I can help direct the implementation a little where you may need some input/help 👍
