### ISSUE TITLE
InlineMarkdownConfiguration does not process new lines

### ISSUE THREAD

**Issue by pexavc** [shaps80/MarkdownText#6]
## General Information
Render new lines in paragraphs for a specific?(not sure) edge.

 - Project version:
commit hash: `c5f5e3e7d2de5dbccd7756d6b4b3739fdf427c33`
 
 - Platform/OS version: 
MacOS 12.6
 
 - IDE version:
Xcode 14.2
 
 - Devices: 
 2017 Macbook Pro

 - Any related GitHub issues:

## Describe the bug
Rendering Paragraph text with ` \` new line markers

## Steps to reproduce
```
text\
text2\
text3
```

## Expected behavior
```
text
text2
text3
```

## Simple Fix, but not sure if holistic enough

`InlineStyle.swift`

within `struct InlineMarkdownConfiguration`

starting if condition
```swift
if component.content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
    return result = result + Text("\n")
} 
```

entire `var body: some View` 

```swift
elements.reduce(into: Text("")) { result, component in
    if component.content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
        return result = result + Text("\n")
    } else if component.attributes.contains(.code) {
        return result = result + code.makeBody(
            configuration: .init(code: component.content, font: font)
        )
    } else {
        return result = result + Text(component.content).apply(
            strong: strong,
            emphasis: emphasis,
            strikethrough: strikethrough,
            link: link,
            attributes: component.attributes
        )
    }
}
```

**Comment by shaps80** [comment]
Hi thanks for this! I’m not sure I fully understand what this is about I’m afraid.
Can you elaborate? Also I’d be happy for you to post a PR and I can take a look at it running, see if I can understand your issue. Thanks.

**Comment by pexavc** [comment]
> Hi thanks for this! I’m not sure I fully understand what this is about I’m afraid. Can you elaborate? Also I’d be happy for you to post a PR and I can take a look at it running, see if I can understand your issue. Thanks.

No problem!

I can make a PR too. But essentially, I was receiving text from a server that was adding new lines with this `\` notation I believe. The output from the MarkdownText was presenting the response in 1 line instead of multiple lines for instance. The `\` was being seen as just an empty string. So applied that hacky solution above. But, I felt other cases of MarkdownText was still being rendered properly during my minimal testing.

The Document class from `swift-markdown` was detecting the line range to be > 1 too. So I felt this `InlineMarkdownStyle` was not detecting it. The entire tree was multiple Inlines inside of a Paragraph

Confirmed that by doing this:
```swift
let doc = Document(parsing: markdown, source: source)
let elements = MarkdownTextBuilder(
    document: doc
).blockElements

content = .init(elements: elements, paragraphSpacing: paragraphSpacing, isLazy: true)

let lineCount = Int(doc.range?.upperBound.line ?? 0)
```

over here:

https://github.com/shaps80/MarkdownText/blob/c5f5e3e7d2de5dbccd7756d6b4b3739fdf427c33/Sources/MarkdownText/MarkdownText.swift#L19-L23

**Comment by pexavc** [comment]
Posted a PR here https://github.com/shaps80/MarkdownText/pull/7

**Comment by shaps80** [comment]
Right I think I understand now. The underlying library that passes the markdown is provided by Apple so this could be an issue there. My styling library should not be handling these types of details.

I may also be behind in terms of the latest version for the library, so I’ll try updating that and put it on a branch. You can you retest with 👍

**Comment by pexavc** [comment]
> Right I think I understand now. The underlying library that passes the markdown is provided by Apple so this could be an issue there. My styling library should not be handling these types of details.
> 
> I may also be behind in terms of the latest version for the library, so I’ll try updating that and put it on a branch. You can you retest with 👍

Oh great, thank you! Will look forward to testing it.
